# Generated by Django 5.0.6 on 2026-03-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parentuser",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to.",
                related_name="accounts_parentuser_set",
                related_query_name="accounts_parentuser",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AlterField(
            model_name="parentuser",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="accounts_parentuser_set",
                related_query_name="accounts_parentuser",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
    ]
