# Generated by Django 5.2.12 on 2026-03-05 15:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_fix_token_blacklist_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="parentuser",
            name="confirmation_token",
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name="parentuser",
            name="confirmation_token_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="parentuser",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
    ]
