# Generated by Django 5.2.12 on 2026-03-13 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_parentuser_confirmation_token_and_more"),
        ("rewards", "0002_rank"),
    ]

    operations = [
        migrations.AddField(
            model_name="childprofile",
            name="current_rank",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="rewards.rank",
            ),
        ),
    ]
