# Generated by Django 5.2.12 on 2026-03-05 15:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0003_fix_token_blacklist_uuid"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoryArc",
            fields=[
                ("id", models.SlugField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                (
                    "arc_type",
                    models.CharField(
                        choices=[
                            ("prologue", "Prologue"),
                            ("mission_intro", "Mission Intro"),
                            ("mission_outro", "Mission Outro"),
                            ("interlude", "Interlude"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Global display order for arc lists"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Scene",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("order", models.IntegerField()),
                ("title", models.CharField(blank=True, max_length=120)),
                (
                    "background_key",
                    models.CharField(
                        help_text="Asset key for background image", max_length=80
                    ),
                ),
                (
                    "characters_on_screen",
                    models.JSONField(
                        default=list,
                        help_text='[{"assetKey": "byte-idle", "position": "center", "motion": "slide-in-left"}]',
                    ),
                ),
                (
                    "bubbles",
                    models.JSONField(
                        default=list,
                        help_text='[{"speaker": "byte", "text": "Hello!", "type": "speech"}]',
                    ),
                ),
                (
                    "motions",
                    models.JSONField(
                        default=list,
                        help_text='[{"target": "screen", "effect": "shake", "duration": 500}]',
                    ),
                ),
                (
                    "music_key",
                    models.CharField(
                        blank=True,
                        help_text="Background music asset key",
                        max_length=80,
                    ),
                ),
                (
                    "sfx_keys",
                    models.JSONField(default=list, help_text='["typing", "whoosh"]'),
                ),
                (
                    "next_action",
                    models.CharField(
                        choices=[
                            ("next", "Next scene"),
                            ("choice", "Player choice"),
                            ("run_code", "Run code button"),
                            ("end", "End of arc"),
                        ],
                        default="next",
                        max_length=20,
                    ),
                ),
                (
                    "action_payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Extra data for next_action, e.g. {"starterCode": "print()", "language": "python"}',
                    ),
                ),
                (
                    "arc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scenes",
                        to="story.storyarc",
                    ),
                ),
            ],
            options={
                "ordering": ["arc", "order"],
                "unique_together": {("arc", "order")},
            },
        ),
        migrations.CreateModel(
            name="SceneProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scene_progress",
                        to="accounts.childprofile",
                    ),
                ),
                (
                    "scene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to="story.scene",
                    ),
                ),
            ],
            options={
                "unique_together": {("child", "scene")},
            },
        ),
    ]
