# Generated by Django 5.2.12 on 2026-03-07 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("story", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scene",
            name="next_action",
            field=models.CharField(
                choices=[
                    ("next", "Next Scene"),
                    ("choice", "Player Choice"),
                    ("run_code", "Run Code Challenge"),
                    ("challenge", "Inline Challenge"),
                    ("end", "End Arc"),
                ],
                default="next",
                max_length=20,
            ),
        ),
    ]
