# Generated by Django 5.2.12 on 2026-03-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rewards", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rank",
            fields=[
                ("slug", models.SlugField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=200)),
                ("emoji", models.CharField(max_length=10)),
                ("min_missions", models.PositiveIntegerField(unique=True)),
                ("color", models.CharField(max_length=7)),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
