# Generated by Django 5.0.6 on 2026-03-04 13:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("characters", "0001_initial"),
        ("rewards", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mission",
            fields=[
                ("id", models.SlugField(primary_key=True, serialize=False)),
                ("num", models.IntegerField()),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("long_description", models.TextField()),
                ("difficulty", models.CharField(max_length=20)),
                ("xp", models.IntegerField()),
                ("coins", models.IntegerField(default=0)),
                ("skills", models.JSONField(default=list)),
                ("mentor_tip", models.TextField()),
                ("why_learn_this", models.TextField()),
                ("estimated_minutes", models.IntegerField()),
                ("starter_code", models.TextField()),
                ("language", models.CharField(max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="missions",
                        to="characters.character",
                    ),
                ),
                (
                    "unlock_after",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="missions.mission",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MissionProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("locked", "locked"),
                            ("available", "available"),
                            ("in_progress", "in_progress"),
                            ("completed", "completed"),
                        ],
                        default="locked",
                        max_length=20,
                    ),
                ),
                ("progress", models.IntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("current_code", models.TextField(blank=True)),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mission_progress",
                        to="accounts.childprofile",
                    ),
                ),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_progress",
                        to="missions.mission",
                    ),
                ),
            ],
            options={
                "unique_together": {("child", "mission")},
            },
        ),
        migrations.CreateModel(
            name="MissionReward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=20)),
                ("label", models.CharField(max_length=50)),
                ("value", models.IntegerField()),
                (
                    "badge",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="rewards.badge",
                    ),
                ),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rewards",
                        to="missions.mission",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MissionStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("num", models.IntegerField()),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("hint", models.TextField(blank=True)),
                ("validation_type", models.CharField(max_length=30)),
                ("validation_value", models.TextField()),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="missions.mission",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StepProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=20)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "mission_progress",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="step_progress",
                        to="missions.missionprogress",
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="missions.missionstep",
                    ),
                ),
            ],
        ),
    ]
