# Generated by Django 5.2.12 on 2026-03-05 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("missions", "0001_initial"),
        ("story", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mission",
            name="intro_arc",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="intro_for_missions",
                to="story.storyarc",
            ),
        ),
        migrations.AddField(
            model_name="mission",
            name="outro_arc",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="outro_for_missions",
                to="story.storyarc",
            ),
        ),
        migrations.AddField(
            model_name="mission",
            name="requires_arc",
            field=models.ForeignKey(
                blank=True,
                help_text="Child must complete this arc before starting the mission",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="unlocks_missions",
                to="story.storyarc",
            ),
        ),
    ]
