# Generated by Django 5.2.12 on 2026-03-07 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("missions", "0002_mission_intro_arc_mission_outro_arc_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="missionstep",
            name="content",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Step content — structure depends on step_type",
            ),
        ),
        migrations.AddField(
            model_name="missionstep",
            name="step_type",
            field=models.CharField(
                choices=[
                    ("story", "Story"),
                    ("speech_bubble_fill", "Speech Bubble Fill"),
                    ("multiple_choice", "Multiple Choice"),
                    ("drag_and_drop", "Drag and Drop"),
                    ("command_sequence", "Command Sequence"),
                    ("matching", "Matching"),
                    ("true_false", "True/False"),
                    ("code_editor_challenge", "Code Editor Challenge"),
                    ("debug_task", "Debug Task"),
                    ("mini_project", "Mini Project"),
                    ("boss_battle_phase", "Boss Battle Phase"),
                ],
                default="story",
                max_length=30,
            ),
        ),
    ]
