# Generated by Django 5.2.12 on 2026-03-07 08:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_parentuser_confirmation_token_and_more"),
        ("characters", "0001_initial"),
        ("missions", "0003_missionstep_content_missionstep_step_type"),
        ("story", "0002_alter_scene_next_action"),
    ]

    operations = [
        migrations.CreateModel(
            name="BossBattle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("total_phases", models.PositiveIntegerField(default=3)),
                (
                    "defeat_dialogue",
                    models.JSONField(
                        default=list, help_text="Dialogue shown on phase failure"
                    ),
                ),
                (
                    "xp_bonus",
                    models.PositiveIntegerField(
                        default=100, help_text="Bonus XP on top of mission XP"
                    ),
                ),
                (
                    "intro_arc",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="boss_intro",
                        to="story.storyarc",
                    ),
                ),
                (
                    "mission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boss_battle",
                        to="missions.mission",
                    ),
                ),
                (
                    "victory_arc",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="boss_victory",
                        to="story.storyarc",
                    ),
                ),
            ],
            options={
                "verbose_name": "Boss Battle",
            },
        ),
        migrations.CreateModel(
            name="BossBattlePhase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("phase_number", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "challenge_type",
                    models.CharField(
                        choices=[
                            ("story", "Story"),
                            ("speech_bubble_fill", "Speech Bubble Fill"),
                            ("multiple_choice", "Multiple Choice"),
                            ("drag_and_drop", "Drag and Drop"),
                            ("command_sequence", "Command Sequence"),
                            ("matching", "Matching"),
                            ("true_false", "True/False"),
                            ("code_editor_challenge", "Code Editor Challenge"),
                            ("debug_task", "Debug Task"),
                            ("mini_project", "Mini Project"),
                            ("boss_battle_phase", "Boss Battle Phase"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "content",
                    models.JSONField(
                        default=dict, help_text="Same schema as MissionStep.content"
                    ),
                ),
                (
                    "intro_dialogue",
                    models.JSONField(
                        default=list, help_text="Character dialogue before phase"
                    ),
                ),
                (
                    "success_dialogue",
                    models.JSONField(
                        default=list, help_text="Character dialogue on phase clear"
                    ),
                ),
                (
                    "health_bar_label",
                    models.CharField(
                        default="Dr. Glitch",
                        help_text="Boss health bar label",
                        max_length=100,
                    ),
                ),
                (
                    "boss_battle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phases",
                        to="missions.bossbattle",
                    ),
                ),
                (
                    "leader_character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="characters.character",
                    ),
                ),
            ],
            options={
                "ordering": ["phase_number"],
                "unique_together": {("boss_battle", "phase_number")},
            },
        ),
        migrations.CreateModel(
            name="BossBattleProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("current_phase", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "boss_battle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to="missions.bossbattle",
                    ),
                ),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boss_progress",
                        to="accounts.childprofile",
                    ),
                ),
            ],
            options={
                "unique_together": {("child", "boss_battle")},
            },
        ),
    ]
