# Generated by Django 5.0.6 on 2026-03-04 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LearningTrack",
            fields=[
                ("id", models.SlugField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("icon", models.CharField(max_length=10)),
                ("color", models.CharField(max_length=7)),
                ("order", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="LessonProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                ("id", models.SlugField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("duration", models.CharField(max_length=20)),
                ("order", models.IntegerField(default=0)),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="academy.learningtrack",
                    ),
                ),
                (
                    "unlock_after",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="academy.lesson",
                    ),
                ),
            ],
        ),
    ]
