# Generated by Django 5.2.12 on 2026-03-07 03:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0002_initial"),
        ("accounts", "0004_parentuser_confirmation_token_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LessonStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                (
                    "step_type",
                    models.CharField(
                        choices=[
                            ("explanation", "Explanation"),
                            ("example", "Example"),
                            ("guided_coding", "Guided Coding"),
                            ("multiple_choice", "Multiple Choice"),
                            ("fill_in", "Fill In"),
                            ("debugging", "Debugging"),
                            ("checkpoint", "Checkpoint Question"),
                            ("mini_challenge", "Mini Challenge"),
                            ("reflection", "Reflection"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.JSONField(default=dict)),
                ("hint", models.TextField(blank=True)),
                ("is_required", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="academy.lesson",
                    ),
                ),
            ],
            options={
                "ordering": ["number"],
                "unique_together": {("lesson", "number")},
            },
        ),
        migrations.CreateModel(
            name="LessonStepProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("locked", "Locked"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                        ],
                        default="locked",
                        max_length=20,
                    ),
                ),
                ("submitted_answer", models.JSONField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_step_progress",
                        to="accounts.childprofile",
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to="academy.lessonstep",
                    ),
                ),
            ],
            options={
                "unique_together": {("child", "step")},
            },
        ),
    ]
