# Generated by Django 5.2.12 on 2026-03-13 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0003_lessonstep_lessonstepprogress"),
        ("characters", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningtrack",
            name="character",
            field=models.ForeignKey(
                blank=True,
                help_text="The SHERO character who teaches this track",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tracks",
                to="characters.character",
            ),
        ),
    ]
